### PR TITLE
Week2 tasks completed

### PR DESCRIPTION
**Pull request by jamyyu**
游如婕
http://52.27.229.14:8000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your code will load the same page multiple times if we scroll down and up quickly.
未命名-2

**Comment by jamyyu** [comment]
Fix: Prevent multiple page loads on quick scroll

**Comment by jamyyu** [comment]
Fix: Prevent multiple page loads on quick scroll

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
